ALTER TABLE IF EXISTS admin_navigation_item
    ADD COLUMN IF NOT EXISTS required_role VARCHAR(20) DEFAULT 'USER' NOT NULL;

ALTER TABLE IF EXISTS payment_transaction
    ADD COLUMN IF NOT EXISTS pg_provider VARCHAR(40) DEFAULT 'MOCK' NOT NULL;

ALTER TABLE IF EXISTS payment_transaction
    ADD COLUMN IF NOT EXISTS approval_request_key VARCHAR(120);

ALTER TABLE IF EXISTS payment_transaction
    ADD COLUMN IF NOT EXISTS version BIGINT;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS pg_provider VARCHAR(40);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS event_type VARCHAR(40);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS tid VARCHAR(120);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(120);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS http_status INTEGER;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS success_yn BOOLEAN;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS duration_ms BIGINT;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS error_message VARCHAR(300);

CREATE TABLE IF NOT EXISTS payment_recovery_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    task_key VARCHAR(160) NOT NULL,
    payment_id BIGINT,
    cancel_id BIGINT,
    order_no VARCHAR(80),
    tid VARCHAR(120),
    idempotency_key VARCHAR(120),
    recovery_type VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    retry_count INTEGER NOT NULL,
    max_retry_count INTEGER NOT NULL,
    last_error_message VARCHAR(300),
    last_tried_at TIMESTAMP,
    processed_at TIMESTAMP,
    CONSTRAINT uk_payment_recovery_task_key UNIQUE (task_key)
);

CREATE TABLE IF NOT EXISTS alimtalk_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    payment_id BIGINT NOT NULL,
    sales_id BIGINT,
    message_key VARCHAR(120) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    retry_count INTEGER NOT NULL,
    max_retry_count INTEGER DEFAULT 5 NOT NULL,
    last_error_message VARCHAR(300),
    processing_started_at TIMESTAMP,
    sent_at TIMESTAMP,
    CONSTRAINT uk_alimtalk_queue_message_key UNIQUE (message_key)
);

ALTER TABLE IF EXISTS external_send_request
    ADD COLUMN IF NOT EXISTS max_retry_count INTEGER DEFAULT 5 NOT NULL;

ALTER TABLE IF EXISTS external_send_request
    ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMP;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS payment_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS cancel_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS original_sales_transaction_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS pg_transaction_id VARCHAR(120);

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS supply_amount NUMERIC(19, 2) DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS total_amount NUMERIC(19, 2) DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS ledger_status VARCHAR(30) DEFAULT 'POSTED' NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS settlement_status VARCHAR(30) DEFAULT 'NOT_SETTLED' NOT NULL;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS pg_code VARCHAR(40);

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(40);

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS seller_id BIGINT;

ALTER TABLE IF EXISTS sales_transaction
    ADD COLUMN IF NOT EXISTS order_item_id BIGINT;

UPDATE sales_transaction
SET pg_transaction_id = tid
WHERE pg_transaction_id IS NULL;

UPDATE sales_transaction
SET total_amount = sale_amount
WHERE total_amount = 0;

UPDATE sales_transaction
SET supply_amount = ROUND(total_amount * 10 / 11, 0),
    vat_amount = total_amount - ROUND(total_amount * 10 / 11, 0)
WHERE supply_amount = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_transaction_approval_key_idx
    ON payment_transaction (approval_request_key);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_transaction_order_no_idx
    ON payment_transaction (order_no);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_transaction_tid_idx
    ON payment_transaction (tid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_cancel_request_key_idx
    ON payment_cancel (cancel_request_key);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sales_transaction_source_idx
    ON sales_transaction (source_type, source_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_external_send_request_key_idx
    ON external_send_request (request_key);

CREATE UNIQUE INDEX IF NOT EXISTS uk_alimtalk_queue_message_key_idx
    ON alimtalk_queue (message_key);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_recovery_task_key_idx
    ON payment_recovery_task (task_key);
