ALTER TABLE IF EXISTS admin_navigation_item
    ADD COLUMN IF NOT EXISTS required_role VARCHAR(20) DEFAULT 'USER' NOT NULL;

ALTER TABLE IF EXISTS payment_transaction
    ADD COLUMN IF NOT EXISTS pg_provider VARCHAR(40) DEFAULT 'MOCK' NOT NULL;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS pg_provider VARCHAR(40);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS event_type VARCHAR(40);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS tid VARCHAR(120);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(120);

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS http_status INTEGER;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS success_yn BOOLEAN;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS duration_ms BIGINT;

ALTER TABLE IF EXISTS pg_api_log
    ADD COLUMN IF NOT EXISTS error_message VARCHAR(300);
