spring.application.name=yeni-backoffice

spring.profiles.active=test

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.web.resources.chain.cache=false

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
