COMMENT ON TABLE payment_auth_session IS '표준결제 요청부터 인증 결과 수신 전까지의 결제 인증 세션을 관리합니다.';
COMMENT ON TABLE payment_transaction IS '승인 완료된 결제 거래와 취소 누적 금액, 결제 상태를 관리합니다.';
COMMENT ON TABLE payment_cancel IS '전체/부분 취소 요청과 idempotency key를 관리합니다.';
COMMENT ON TABLE payment_recovery_task IS 'PG 결과불명, 망취소, 외부전송 재처리 등 운영 복구 작업을 관리합니다.';
COMMENT ON TABLE pg_api_log IS 'PG 요청/응답 전문과 처리 결과를 추적합니다.';
COMMENT ON TABLE sales_transaction IS '결제/취소 결과를 매출 데이터로 분리해 정산 대상화합니다.';
COMMENT ON TABLE external_send_request IS '외부 영업관리 시스템 전송 요청을 관리합니다.';
COMMENT ON TABLE external_send_history IS '외부 전송 시도별 요청/응답 이력을 저장합니다.';
COMMENT ON TABLE alimtalk_queue IS '결제/취소/실패 이벤트에 대한 알림톡 발송 대기열을 관리합니다.';
COMMENT ON TABLE pg_fee_policy IS 'PG 수수료율과 적용 기간을 관리합니다.';
COMMENT ON TABLE settlement_statement IS '일별 정산 집계 금액과 정산 상태를 관리합니다.';
COMMENT ON TABLE settlement_detail IS '정산 명세에 포함된 매출 단위 상세를 관리합니다.';
COMMENT ON TABLE settlement_batch_log IS '정산 배치 실행 상태와 처리 건수를 기록합니다.';
COMMENT ON TABLE audit_log IS '결제/매출/정산 주요 액션의 감사 로그를 저장합니다.';

COMMENT ON COLUMN payment_auth_session.id IS '결제 인증 세션 ID';
COMMENT ON COLUMN payment_auth_session.mid IS 'PG 가맹점 ID';
COMMENT ON COLUMN payment_auth_session.order_no IS '내부 주문번호';
COMMENT ON COLUMN payment_auth_session.amount IS '결제 요청 금액';
COMMENT ON COLUMN payment_auth_session.currency IS '통화 코드';
COMMENT ON COLUMN payment_auth_session.buyer_name IS '구매자명';
COMMENT ON COLUMN payment_auth_session.product_name IS '상품명';
COMMENT ON COLUMN payment_auth_session.auth_token IS 'Mock 인증 토큰';
COMMENT ON COLUMN payment_auth_session.status IS '인증 세션 상태';
COMMENT ON COLUMN payment_auth_session.expired_at IS '인증 세션 만료 시각';

COMMENT ON COLUMN payment_transaction.id IS '결제 거래 ID';
COMMENT ON COLUMN payment_transaction.mid IS 'PG 가맹점 ID';
COMMENT ON COLUMN payment_transaction.pg_provider IS 'PG Provider 구분';
COMMENT ON COLUMN payment_transaction.order_no IS '내부 주문번호';
COMMENT ON COLUMN payment_transaction.tid IS 'PG 거래번호';
COMMENT ON COLUMN payment_transaction.approval_request_key IS '중복 승인 방지 키';
COMMENT ON COLUMN payment_transaction.approved_amount IS '승인 금액';
COMMENT ON COLUMN payment_transaction.canceled_amount IS '누적 취소 금액';
COMMENT ON COLUMN payment_transaction.currency IS '통화 코드';
COMMENT ON COLUMN payment_transaction.payment_status IS '결제 상태';
COMMENT ON COLUMN payment_transaction.approved_at IS '승인 시각';
COMMENT ON COLUMN payment_transaction.failure_reason IS '실패 또는 결과불명 사유';
COMMENT ON COLUMN payment_transaction.version IS '동시성 제어 버전';

COMMENT ON COLUMN payment_cancel.id IS '취소 ID';
COMMENT ON COLUMN payment_cancel.payment_id IS '결제 거래 ID';
COMMENT ON COLUMN payment_cancel.tid IS 'PG 거래번호';
COMMENT ON COLUMN payment_cancel.cancel_request_key IS '중복 취소 방지 키';
COMMENT ON COLUMN payment_cancel.cancel_amount IS '취소 요청 금액';
COMMENT ON COLUMN payment_cancel.cancel_type IS '전체/부분 취소 구분';
COMMENT ON COLUMN payment_cancel.cancel_status IS '취소 처리 상태';
COMMENT ON COLUMN payment_cancel.canceled_at IS '취소 완료 시각';
COMMENT ON COLUMN payment_cancel.cancel_reason IS '취소 사유';

COMMENT ON COLUMN payment_recovery_task.id IS '복구 작업 ID';
COMMENT ON COLUMN payment_recovery_task.task_key IS '복구 작업 중복 방지 키';
COMMENT ON COLUMN payment_recovery_task.payment_id IS '결제 거래 ID';
COMMENT ON COLUMN payment_recovery_task.cancel_id IS '취소 ID';
COMMENT ON COLUMN payment_recovery_task.recovery_type IS '복구 작업 유형';
COMMENT ON COLUMN payment_recovery_task.status IS '복구 작업 상태';
COMMENT ON COLUMN payment_recovery_task.retry_count IS '재시도 횟수';
COMMENT ON COLUMN payment_recovery_task.max_retry_count IS '최대 재시도 횟수';
COMMENT ON COLUMN payment_recovery_task.last_error_message IS '마지막 오류 메시지';
COMMENT ON COLUMN payment_recovery_task.processed_at IS '마지막 처리 시각';

COMMENT ON COLUMN pg_api_log.id IS 'PG API 로그 ID';
COMMENT ON COLUMN pg_api_log.request_id IS '요청 추적 ID';
COMMENT ON COLUMN pg_api_log.payment_id IS '결제 거래 ID';
COMMENT ON COLUMN pg_api_log.order_no IS '내부 주문번호';
COMMENT ON COLUMN pg_api_log.pg_company IS 'PG사 구분';
COMMENT ON COLUMN pg_api_log.pg_provider IS 'PG Provider 구분';
COMMENT ON COLUMN pg_api_log.event_type IS '결제 이벤트 유형';
COMMENT ON COLUMN pg_api_log.api_type IS 'PG API 유형';
COMMENT ON COLUMN pg_api_log.tid IS 'PG 거래번호';
COMMENT ON COLUMN pg_api_log.idempotency_key IS '중복 요청 방지 키';
COMMENT ON COLUMN pg_api_log.request_body IS '민감정보를 제외한 요청 전문';
COMMENT ON COLUMN pg_api_log.response_body IS '민감정보를 제외한 응답 전문';
COMMENT ON COLUMN pg_api_log.result_status IS '로그 처리 결과 상태';
COMMENT ON COLUMN pg_api_log.result_message IS 'PG 처리 결과 메시지';
COMMENT ON COLUMN pg_api_log.http_status IS 'Mock API HTTP 상태';
COMMENT ON COLUMN pg_api_log.success_yn IS '성공 여부';
COMMENT ON COLUMN pg_api_log.duration_ms IS '처리 소요 시간';
COMMENT ON COLUMN pg_api_log.error_message IS '실패 또는 결과불명 원인 메시지';
COMMENT ON COLUMN pg_api_log.logged_at IS '로그 기록 시각';

COMMENT ON COLUMN sales_transaction.id IS '매출 ID';
COMMENT ON COLUMN sales_transaction.source_type IS 'SALE 또는 CANCEL 원천 유형';
COMMENT ON COLUMN sales_transaction.source_id IS '원천 데이터 ID';
COMMENT ON COLUMN sales_transaction.order_no IS '내부 주문번호';
COMMENT ON COLUMN sales_transaction.tid IS 'PG 거래번호';
COMMENT ON COLUMN sales_transaction.sale_type IS 'SALE/CANCEL 매출 유형';
COMMENT ON COLUMN sales_transaction.sale_amount IS '매출 금액';
COMMENT ON COLUMN sales_transaction.vat_amount IS 'VAT 금액';
COMMENT ON COLUMN sales_transaction.sale_status IS '매출 처리 상태';
COMMENT ON COLUMN sales_transaction.business_date IS '정산 기준 영업일';
COMMENT ON COLUMN sales_transaction.occurred_at IS '매출 발생 시각';
COMMENT ON COLUMN sales_transaction.external_send_required IS '외부 전송 필요 여부';
COMMENT ON COLUMN sales_transaction.settlement_included_yn IS '정산 포함 여부';

COMMENT ON COLUMN external_send_request.id IS '외부 전송 요청 ID';
COMMENT ON COLUMN external_send_request.sales_id IS '매출 ID';
COMMENT ON COLUMN external_send_request.request_key IS '외부 전송 중복 방지 키';
COMMENT ON COLUMN external_send_request.target_system IS '전송 대상 시스템';
COMMENT ON COLUMN external_send_request.send_status IS '전송 상태';
COMMENT ON COLUMN external_send_request.retry_count IS '재시도 횟수';
COMMENT ON COLUMN external_send_request.last_error_message IS '마지막 전송 오류 메시지';
COMMENT ON COLUMN external_send_request.last_sent_at IS '마지막 전송 시각';

COMMENT ON COLUMN external_send_history.id IS '외부 전송 이력 ID';
COMMENT ON COLUMN external_send_history.send_request_id IS '외부 전송 요청 ID';
COMMENT ON COLUMN external_send_history.target_system IS '전송 대상 시스템';
COMMENT ON COLUMN external_send_history.request_body IS '전송 요청 내용';
COMMENT ON COLUMN external_send_history.response_body IS '전송 응답 내용';
COMMENT ON COLUMN external_send_history.result_status IS '전송 결과 상태';
COMMENT ON COLUMN external_send_history.result_message IS '전송 결과 메시지';
COMMENT ON COLUMN external_send_history.sent_at IS '전송 시각';

COMMENT ON COLUMN alimtalk_queue.id IS '알림톡 Queue ID';
COMMENT ON COLUMN alimtalk_queue.payment_id IS '결제 거래 ID';
COMMENT ON COLUMN alimtalk_queue.sales_id IS '매출 ID';
COMMENT ON COLUMN alimtalk_queue.message_key IS '알림톡 중복 발송 방지 키';
COMMENT ON COLUMN alimtalk_queue.event_type IS '알림톡 이벤트 유형';
COMMENT ON COLUMN alimtalk_queue.status IS '알림톡 발송 상태';
COMMENT ON COLUMN alimtalk_queue.retry_count IS '재시도 횟수';
COMMENT ON COLUMN alimtalk_queue.last_error_message IS '마지막 발송 오류 메시지';
COMMENT ON COLUMN alimtalk_queue.sent_at IS '발송 시각';

COMMENT ON COLUMN pg_fee_policy.id IS '수수료 정책 ID';
COMMENT ON COLUMN pg_fee_policy.pg_company IS 'PG사';
COMMENT ON COLUMN pg_fee_policy.mid IS '가맹점 ID';
COMMENT ON COLUMN pg_fee_policy.payment_method IS '결제수단';
COMMENT ON COLUMN pg_fee_policy.fee_rate IS '수수료율';
COMMENT ON COLUMN pg_fee_policy.effective_start_date IS '적용 시작일';
COMMENT ON COLUMN pg_fee_policy.effective_end_date IS '적용 종료일';
COMMENT ON COLUMN pg_fee_policy.use_yn IS '사용 여부';

COMMENT ON COLUMN settlement_statement.id IS '정산 명세 ID';
COMMENT ON COLUMN settlement_statement.settlement_date IS '정산 기준일';
COMMENT ON COLUMN settlement_statement.pg_company IS 'PG사';
COMMENT ON COLUMN settlement_statement.mid IS '가맹점 ID';
COMMENT ON COLUMN settlement_statement.gross_amount IS '총 매출 금액';
COMMENT ON COLUMN settlement_statement.fee_amount IS 'PG 수수료';
COMMENT ON COLUMN settlement_statement.vat_amount IS '수수료 VAT';
COMMENT ON COLUMN settlement_statement.net_amount IS '지급 예정 금액';
COMMENT ON COLUMN settlement_statement.settlement_status IS '정산 상태';

COMMENT ON COLUMN settlement_detail.id IS '정산 상세 ID';
COMMENT ON COLUMN settlement_detail.settlement_statement_id IS '정산 명세 ID';
COMMENT ON COLUMN settlement_detail.sales_id IS '매출 ID';
COMMENT ON COLUMN settlement_detail.sale_type IS 'SALE/CANCEL 매출 유형';
COMMENT ON COLUMN settlement_detail.sale_amount IS '매출 금액';
COMMENT ON COLUMN settlement_detail.fee_amount IS '수수료';
COMMENT ON COLUMN settlement_detail.net_amount IS '차감 후 금액';

COMMENT ON COLUMN settlement_batch_log.id IS '배치 로그 ID';
COMMENT ON COLUMN settlement_batch_log.target_date IS '배치 대상일';
COMMENT ON COLUMN settlement_batch_log.batch_status IS '배치 상태';
COMMENT ON COLUMN settlement_batch_log.target_count IS '대상 건수';
COMMENT ON COLUMN settlement_batch_log.success_count IS '성공 건수';
COMMENT ON COLUMN settlement_batch_log.failure_count IS '실패 건수';
COMMENT ON COLUMN settlement_batch_log.error_message IS '배치 실패 메시지';
COMMENT ON COLUMN settlement_batch_log.started_at IS '배치 시작 시각';
COMMENT ON COLUMN settlement_batch_log.ended_at IS '배치 종료 시각';

COMMENT ON COLUMN audit_log.id IS '감사 로그 ID';
COMMENT ON COLUMN audit_log.domain_type IS '도메인 구분';
COMMENT ON COLUMN audit_log.action_type IS '행위 구분';
COMMENT ON COLUMN audit_log.reference_key IS '참조 키';
COMMENT ON COLUMN audit_log.description IS '처리 설명';
COMMENT ON COLUMN audit_log.logged_at IS '로그 기록 시각';
