package com.yeni.backoffice.core.payment.enums;

public enum PaymentStatus {
    READY,
    APPROVE_REQUESTED,
    APPROVED,
    APPROVE_FAILED,
    APPROVE_UNKNOWN,
    CANCEL_REQUESTED,
    PARTIAL_CANCELED,
    CANCELED,
    CANCEL_FAILED,
    CANCEL_UNKNOWN,
    CANCEL_RECONCILE_REQUIRED,
    NETWORK_CANCEL_REQUIRED,
    NETWORK_CANCEL_SUCCESS,
    NETWORK_CANCEL_FAILED,
    UNKNOWN
}
